version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_ALLOW_EMPTY_PASSWORD="true"
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    expose:
      - $MYSQLDB_LOCAL_PORT
      - $MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      # this runs the init script of the database
      # - "./scripts/schema.sql:/docker-entrypoint-initdb.d/init_db.sql"
      # - ./init:/docker-entrypoint-initdb.d
  db_seeder:
    image: mysql:latest
    volumes:
      - ./init_db.sql:/init_db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    entrypoint: [ "bash", "-c", "sleep 3 && mysql --user=root --host=mysqldb --password=$MYSQLDB_ROOT_PASSWORD --port=3306 bikeapp < /init_db.sql && exit"] 
    depends_on:
      - mysqldb
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    links:
      - mysqldb:mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    # tty: true

volumes: 
  db: